export const productCardData = [
  {
    title: `Wooden water bottle`,
    oldPrice: `रु 4000`,
    newPrice: `रु 2000.00`,
    price: 2000,
    category: "Bottles",
    material: "Wood",
    rating: 4.6,
    desc1: `Natural Wood - Small`,
    desc2: `Natural wooden bottle, handcrafted.`,
    images: [
      `/images/wooden-bottle2.jpg`,
      `/images/wood-bottle.png`,
      `/images/Water-Bottle-Wood.jpg`,
    ],
   
  },
  {
    title: `Beeswax Food Wraps`,
    oldPrice: `रु 4000`,
    newPrice: `रु 2000.00`,
    price: 2000,
    category: "Kitchen",
    material: "Beeswax",
    rating: 4.2,
    desc1: `Reusable food wrap`,
    images: [`/images/beeswax-food-wrap.jpg`, `/images/Beeswax_Wrap_quickView.jpg`] 
  },
  {
    title: `Cloth Bag`,
    oldPrice: `रु 4000`,
    newPrice: `रु 800.00`,
    price: 800,
    category: "Accessories",
    material: "Fabric",
    rating: 4.0,
    desc1: `Reusable tote bag`,
    images: [`/images/tote-bag.jpg`, `/images/tote-bag-quic-view.jpg`]
  },
  {
    title: `Bamboo Straws`,
    oldPrice: `रु 4000`,
    newPrice: `रु 250.00`,
    price: 250,
    category: "Accessories",
    material: "Bamboo",
    rating: 4.4,
    desc1: `Set of bamboo straws`,
    images: [`/images/bamboo-straws.jpg`, `/images/bamboo_straws_quick-view.jpg`]
  },
  {
    title: `Wooden Toothbrush`,
    oldPrice: `रु 4000`,
    newPrice: `रु 350.00`,
    price: 350,
    category: "Bath",
    material: "Wood",
    rating: 4.1,
    desc1: `Biodegradable wooden toothbrush`,
    images: [`/images/toothbrush.jpg`, `/images/toothbrush-quick-view.webp`]
  },
  {
    title: `Disposable Trash Bags`,
    oldPrice: `रु 4000`,
    newPrice: `रु 120.00`,
    price: 120,
    category: "Home",
    material: "Compostable",
    rating: 3.9,
    desc1: `Compostable trash bags`,
    productImage: `/images/Disposable-trash-bags.jpg`,
  },
  {
    title: `Wooden Comb`,
    oldPrice: `रु 4000`,
    newPrice: `रु 300.00`,
    price: 300,
    category: "Bath",
    material: "Wood",
    rating: 4.3,
    desc1: `Neem wooden comb`,
    productImage: `/images/neem-wooden-comb.jpg`,
  },
  {
    title: `Laundry Sheets`,
    oldPrice: `रु 4000`,
    newPrice: `रु 450.00`,
    price: 450,
    category: "Laundry",
    material: "Plant-based",
    rating: 4.5,
    desc1: `Concentrated laundry sheets`,
    productImage: `/images/laundry-sheets.jpg`,
  },
  {
    title: `Eco-friendly Comb (S)`,
    oldPrice: `रु 4000`,
    newPrice: `रु 300.00`,
    price: 300,
    category: "Bath",
    material: "Wood",
    rating: 4.0,
    desc1: `Small eco comb`,
    productImage: `/images/beeswax-food-wrap.jpg`,
  },
  {
    title: `Eco-friendly Comb (M)`,
    oldPrice: `RS 4000`,
    newPrice: `2000`,
    price: 2000,
    category: "Bath",
    material: "Wood",
    rating: 3.8,
    desc1: `Medium eco comb`,
    productImage: `/images/beeswax-food-wrap.jpg`,
  },
  {
    title: `Eco-friendly Comb (L)`,
    oldPrice: `RS 4000`,
    newPrice: `2000`,
    price: 2000,
    category: "Bath",
    material: "Wood",
    rating: 3.8,
    desc1: `Large eco comb`,
    productImage: `/images/beeswax-food-wrap.jpg`,
  },
  {
    title: `Eco-friendly Comb (XL)`,
    oldPrice: `RS 4000`,
    newPrice: `2000`,
    price: 2000,
    category: "Bath",
    material: "Wood",
    rating: 3.8,
    desc1: `Extra-large eco comb`,
    productImage: `/images/beeswax-food-wrap.jpg`,
  },
];
